// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tuple.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	tuple.proto

It has these top-level messages:
	SPOTuple
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// core message type for lowest-level data tuples
type SPOTuple struct {
	Subject   string `protobuf:"bytes,1,opt,name=Subject" json:"Subject,omitempty"`
	Object    string `protobuf:"bytes,2,opt,name=Object" json:"Object,omitempty"`
	Predicate string `protobuf:"bytes,3,opt,name=Predicate" json:"Predicate,omitempty"`
	Version   int64  `protobuf:"varint,4,opt,name=Version" json:"Version,omitempty"`
	Context   string `protobuf:"bytes,5,opt,name=Context" json:"Context,omitempty"`
	User      string `protobuf:"bytes,6,opt,name=User" json:"User,omitempty"`
	Signature string `protobuf:"bytes,7,opt,name=Signature" json:"Signature,omitempty"`
	MsgID     string `protobuf:"bytes,8,opt,name=MsgID" json:"MsgID,omitempty"`
}

func (m *SPOTuple) Reset()                    { *m = SPOTuple{} }
func (m *SPOTuple) String() string            { return proto.CompactTextString(m) }
func (*SPOTuple) ProtoMessage()               {}
func (*SPOTuple) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SPOTuple) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SPOTuple) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *SPOTuple) GetPredicate() string {
	if m != nil {
		return m.Predicate
	}
	return ""
}

func (m *SPOTuple) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SPOTuple) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *SPOTuple) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SPOTuple) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *SPOTuple) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func init() {
	proto.RegisterType((*SPOTuple)(nil), "pb.SPOTuple")
}

func init() { proto.RegisterFile("tuple.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xbd, 0x0e, 0x82, 0x30,
	0x14, 0x46, 0x53, 0xfe, 0xa9, 0x5b, 0x63, 0xcc, 0x1d, 0x1c, 0x88, 0x13, 0x93, 0x8b, 0x8f, 0xa0,
	0x8b, 0x83, 0x81, 0x80, 0xba, 0x03, 0xde, 0x10, 0x8c, 0xa1, 0xa4, 0x5c, 0x12, 0x9f, 0xd4, 0xe7,
	0x31, 0x6d, 0x41, 0xb7, 0x9e, 0x73, 0x92, 0x7e, 0xb9, 0x7c, 0x45, 0xd3, 0xf0, 0xc2, 0xfd, 0xa0,
	0x24, 0x49, 0xe1, 0x0c, 0xf5, 0xee, 0xc3, 0x78, 0x54, 0xe6, 0xd9, 0x55, 0x6b, 0x01, 0x3c, 0x2c,
	0xa7, 0xfa, 0x89, 0x0d, 0x01, 0x4b, 0x58, 0x1a, 0x17, 0x0b, 0x8a, 0x0d, 0x0f, 0x32, 0x1b, 0x1c,
	0x13, 0x66, 0x12, 0x5b, 0x1e, 0xe7, 0x0a, 0x1f, 0x5d, 0x53, 0x11, 0x82, 0x6b, 0xd2, 0x5f, 0xe8,
	0xff, 0xee, 0xa8, 0xc6, 0x4e, 0xf6, 0xe0, 0x25, 0x2c, 0x75, 0x8b, 0x05, 0x75, 0x39, 0xca, 0x9e,
	0xf0, 0x4d, 0xe0, 0xdb, 0xa5, 0x19, 0x85, 0xe0, 0xde, 0x6d, 0x44, 0x05, 0x81, 0xd1, 0xe6, 0xad,
	0x57, 0xca, 0xae, 0xed, 0x2b, 0x9a, 0x14, 0x42, 0x68, 0x57, 0x7e, 0x42, 0xac, 0xb9, 0x7f, 0x19,
	0xdb, 0xf3, 0x09, 0x22, 0x53, 0x2c, 0xd4, 0x81, 0xb9, 0xf1, 0xf0, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x50, 0xa7, 0xc6, 0x5b, 0xf2, 0x00, 0x00, 0x00,
}
